-- 1. Create the Questions Table
CREATE TABLE public.questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numb INT NOT NULL,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  options JSONB NOT NULL, -- Array of strings
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create the Game Sessions Table
CREATE TABLE public.game_sessions (
  id TEXT PRIMARY KEY DEFAULT 'active-session',
  current_question_index INT DEFAULT 0,
  status TEXT DEFAULT 'LOBBY', -- LOBBY, QUESTION, FINISHED
  timer_start TIMESTAMPTZ,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Initial Session Setup
INSERT INTO public.game_sessions (id, current_question_index, status) 
VALUES ('active-session', 0, 'LOBBY');

-- 4. Enable Real-time for game_sessions
ALTER TABLE public.game_sessions REPLICA IDENTITY FULL;
CREATE PUBLICATION supabase_realtime FOR TABLE public.game_sessions;
